% Function read_parrec(filename,output_format,verbose_flag)
%  to read PARREC files on Philips
%
% Date: 16-nov-2004
% Author: Benoit Desjardins, MD, PhD
%         Department of Radiology
%         University of Michigan
%
%
% Modified for 1, input of parfile name directly
%              2, Data format output selection
%              3, Platform independent file conversion
% JCG 1/27/05
%
%
% 03 Feb 2005, BPR: modified to separate echoes in an additional
% dimension of the data matrix.  Also renamed function to match
% filename
%
% 24 Mar 2005, BPR: kept only the parts that read the PAR file, to
% save some time when we don't need to load in the data itself.
%
%
% Syntax: [parms] = readParBPR(filename,output_format,verboseflag);
%
% Inputs:
%           If no inputs, via UI, select name of PAR file
%           assumes the REC file in the same folder as PAR file
%           output is then FP
%           With inputs:
%                       filename = filename (with path) of PAR file
%                       output_format = data output type - FP, DV, SV
%                       verboseflag = if exists, prints info to command window
%
% Output: flt_data: matrix of the images (as FP values, by default)
%         parms: structure containing PRA file info
%         dims: [stride nline nslice nphase necho ntype ndyn]
% Can process both V3 and V4 types of PAR files automatically
%


function [parms] = readParBPR(parfile,verboseflag);
if nargin < 1
[fname,pname] = uigetfile('*.PAR','Select *.PAR file');
parfile=[pname fname];
end

tic;
[parms,ver] = read_parfile(parfile);

if nargin > 1
    disp(sprintf('This is a %s PAR file',ver));
    disp(sprintf('Output of images is in %s format',out_fmt));
    disp(sprintf('Read %d images of size [%d x %d]',prod(dims(3:end)),dims(1:2)));
    disp(sprintf('# slices: %d, # phases: %d, # echoes: %d, # types: %d, # dynamics: %d',dims(3:end)));
    disp(['Total execution time = ' num2str(toc)]);
end

return;

%==========================================================================

function [parms,ver] = read_parfile(file_name) 

% read all the lines of the PAR file
nlines  = 0;
fid = fopen(file_name,'r');
if (length(fid) < 1), error(['.PAR file ', file_name, ' not found.']); end;
while ~feof(fid)
    curline = fgetl(fid);
    if ~isempty(curline)
        nlines = nlines + 1;
        lines(nlines) = cellstr(curline); % allows variable line size
    end
end
fclose(fid);

% identify the header lines
NG = 0;
for L = 1:size(lines,2)
    curline = char(lines(L));
    if (size(curline,2) > 0 & curline(1) == '.')
       NG = NG + 1;
       geninfo(NG) = lines(L); 
    end
end
if (NG < 1), error('.PAR file has invalid format'); end;

% figure out if V3 or V4 PAR files
test_key = '.    Image pixel size [8 or 16 bits]    :';
if strmatch(test_key,geninfo); % only V3 has that key in the headers
    ver = 'V3';
    template=get_template_v3;
else
    ver = 'V4';
    template=get_template_v4;
end;

% parse the header information
for S=1:size(template,1)
    line_key = char(template(S,1));
    value_type = char(template(S,2));
    field_name = char(template(S,3));
    L = strmatch(line_key,geninfo);

    if ~isempty(L)
        curline = char(geninfo(L));
        value_start = 1 + strfind(curline,':');
        value_end = size(curline,2);
    else
        value_type = ':-( VALUE NOT FOUND )-:';
    end 

    switch (value_type)
    case { 'float scalar' 'int   scalar' 'float vector' 'int   vector'}
         parms.(field_name) = str2num(curline(value_start:value_end));
    case { 'char  scalar' 'char  vector' }
         parms.(field_name) = deblank(strjust(curline(value_start:value_end),'left'));
    otherwise
         parms.(field_name) = '';
    end

end

% parse the tags for each line of data
nimg  = 0;
for L = 1:size(lines,2)
    curline = char(lines(L));
    firstc=curline(1);
    if (size(curline,2) > 0 & firstc ~= '.' & firstc ~= '#' & firstc ~= '*')
       nimg = nimg + 1;
       parms.tags(nimg,:) = str2num(curline);
    end
end
if (nimg < 1), error('Missing scan information in .PAR file'); end;

return;


%==========================================================================
function [template] = get_template_v3;  % header information for V3 PAR files

template = { ...                                  
'.    Patient name                       :'    'char  scalar'    'patient';    ...   
'.    Examination name                   :'    'char  scalar'    'exam_name';   ... 
'.    Protocol name                      :'    'char  vector'    'protocol';   ... 
'.    Examination date/time              :'    'char  vector'    'exam_date';  ...
'.    Acquisition nr                     :'    'int   scalar'    'acq_nr';    ...
'.    Reconstruction nr                  :'    'int   scalar'    'recon_nr';  ...
'.    Scan Duration [sec]                :'    'float scalar'    'scan_dur';        ...
'.    Max. number of cardiac phases      :'    'int   scalar'    'max_card_phases'; ...
'.    Max. number of echoes              :'    'int   scalar'    'max_echoes'; ...
'.    Max. number of slices/locations    :'    'int   scalar'    'max_slices'; ... 
'.    Max. number of dynamics            :'    'int   scalar'    'max_dynamics'; ... 
'.    Max. number of mixes               :'    'int   scalar'    'max_mixes'; ... 
'.    Image pixel size [8 or 16 bits]    :'    'int   scalar'    'pixel_bits'; ... 
'.    Technique                          :'    'char  scalar'    'technique'; ...  
'.    Scan mode                          :'    'char  scalar'    'scan_mode'; ... 
'.    Scan resolution  (x, y)            :'    'int   vector'    'scan_resolution'; ... 
'.    Scan percentage                    :'    'int   scalar'    'scan_percentage'; ... 
'.    Recon resolution (x, y)            :'    'int   vector'    'recon_resolution'; ... 
'.    Number of averages                 :'    'int   scalar'    'num_averages'; ... 
'.    Repetition time [msec]             :'    'float scalar'    'repetition_time'; ...   
'.    FOV (ap,fh,rl) [mm]                :'    'float vector'    'fov'; ... 
'.    Slice thickness [mm]               :'    'float scalar'    'slice_thickness'; ...
'.    Slice gap [mm]                     :'    'float scalar'    'slice_gap'; ... 
'.    Water Fat shift [pixels]           :'    'float scalar'    'water_fat_shift'; ... 
'.    Angulation midslice(ap,fh,rl)[degr]:'    'float vector'    'angulation'; ...
'.    Off Centre midslice(ap,fh,rl) [mm] :'    'float vector'    'offcenter'; ... 
'.    Flow compensation <0=no 1=yes> ?   :'    'int   scalar'    'flowcomp'; ...
'.    Presaturation     <0=no 1=yes> ?   :'    'int   scalar'    'presaturation';... 
'.    Cardiac frequency                  :'    'int   scalar'    'card_frequency'; ...
'.    Min. RR interval                   :'    'int   scalar'    'min_rr_interval'; ...
'.    Max. RR interval                   :'    'int   scalar'    'max_rr_interval'; ...
'.    Phase encoding velocity [cm/sec]   :'    'float vector'    'venc'; ... 
'.    MTC               <0=no 1=yes> ?   :'    'int   scalar'    'mtc'; ...
'.    SPIR              <0=no 1=yes> ?   :'    'int   scalar'    'spir'; ...
'.    EPI factor        <0,1=no EPI>     :'    'int   scalar'    'epi_factor'; ...
'.    TURBO factor      <0=no turbo>     :'    'int   scalar'    'turbo_factor'; ...
'.    Dynamic scan      <0=no 1=yes> ?   :'    'int   scalar'    'dynamic_scan'; ...
'.    Diffusion         <0=no 1=yes> ?   :'    'int   scalar'    'diffusion'; ...
'.    Diffusion echo time [msec]         :'    'float scalar'    'diffusion_echo_time'; ...
'.    Inversion delay [msec]             :'    'float scalar'    'inversion_delay'; ...
};

return;

%==========================================================================
function [template] = get_template_v4;    % header information for V4 PAR files

template = { ...                                  
'.    Patient name                       :' 'char  scalar' 'patient';    ...   
'.    Examination name                   :' 'char  vector' 'exam_name';   ... 
'.    Protocol name                      :' 'char  vector' 'protocol';   ... 
'.    Examination date/time              :' 'char  vector' 'exam_date';  ...
'.    Series Type                        :' 'char  vector' 'series_type';  ...
'.    Acquisition nr                     :' 'int   scalar' 'acq_nr';    ...
'.    Reconstruction nr                  :' 'int   scalar' 'recon_nr';  ...
'.    Scan Duration [sec]                :' 'float scalar' 'scan_dur';        ...
'.    Max. number of cardiac phases      :' 'int   scalar' 'max_card_phases'; ...
'.    Max. number of echoes              :' 'int   scalar' 'max_echoes'; ...
'.    Max. number of slices/locations    :' 'int   scalar' 'max_slices'; ... 
'.    Max. number of dynamics            :' 'int   scalar' 'max_dynamics'; ... 
'.    Max. number of mixes               :' 'int   scalar' 'max_mixes'; ... 
'.    Patient position                   :' 'char  vector' 'patient_position'; ... 
'.    Preparation direction              :' 'char  vector' 'preparation_dir'; ... 
'.    Technique                          :' 'char  scalar' 'technique'; ...  
'.    Scan resolution  (x, y)            :' 'int   vector' 'scan_resolution'; ... 
'.    Scan mode                          :' 'char  scalar' 'scan_mode'; ... 
'.    Repetition time [ms]               :' 'float scalar' 'repetition_time'; ...   
'.    FOV (ap,fh,rl) [mm]                :' 'float vector' 'fov'; ... 
'.    Water Fat shift [pixels]           :' 'float scalar' 'water_fat_shift'; ... 
'.    Angulation midslice(ap,fh,rl)[degr]:' 'float vector' 'angulation'; ...
'.    Off Centre midslice(ap,fh,rl) [mm] :' 'float vector' 'offcenter'; ... 
'.    Flow compensation <0=no 1=yes> ?   :' 'int   scalar' 'flowcomp'; ...
'.    Presaturation     <0=no 1=yes> ?   :' 'int   scalar' 'presaturation';... 
'.    Phase encoding velocity [cm/sec]   :' 'float vector' 'venc'; ... 
'.    MTC               <0=no 1=yes> ?   :' 'int   scalar' 'mtc'; ...
'.    SPIR              <0=no 1=yes> ?   :' 'int   scalar' 'spir'; ...
'.    EPI factor        <0,1=no EPI>     :' 'int   scalar' 'epi_factor'; ...
'.    Dynamic scan      <0=no 1=yes> ?   :' 'int   scalar' 'dynamic_scan'; ...
'.    Diffusion         <0=no 1=yes> ?   :' 'int   scalar' 'diffusion'; ...
'.    Diffusion echo time [msec]         :' 'float scalar' 'diffusion_echo_time'; ...
};

return;

%==========================================================================

